Feat: 경기 일정 API 연결, 경기 세부 결과 선수 스탯
soccer-community-P-C/soccer-community-frontend pull request #32
Opened 2024-06-17 03:55 UTC by PARKmaker

## 개요
경기 일정 API 연결, 경기 세부 결과 선수 스탯

## 작업 사항
- 특정 날짜의 경기 일정 API 임시 연동
- 경기 세부 결과 선수 스탯, 팀 선택 기능

## 관련 이슈

2024-06-17 12:09 UTC, Chuhj requested changes
수고하셨습니다!

2024-06-17 12:09 UTC, Chuhj commented on src/components/Common/table/table-container.tsx
> +  }
클래스를 적용하는 곳에서 삼항연산자를 사용하는게 읽기에 좀 더 편해보이는데 어떻게 생각하시나요?

2024-06-18 05:29 UTC, PARKmaker commented on .env
엇 감사합니다.

2024-06-18 05:29 UTC, PARKmaker commented on src/components/Common/table/table-container.tsx
> +  }
저도 그렇게 하는 게 좋아보이네요 감사합니다.

2024-06-18 06:05 UTC, Chuhj approved these changes

2024-06-18 06:06 UTC, merged